version: '3.8'
services:  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports: 
      - 8001:5000
    volumes: 
    #Edit on changes in directory/docker app 
      - .:/app  
    # extra_hosts:
    # - "host.docker.internal:host-gateway"
    extra_hosts:
      - "otherhost:192.168.0.20"
    depends_on: 
      - db
  queue :
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on: 
      - db
  db :
    image: mysql:5.7.22
    #Incase mysql stops, it would also stop our container so restarting is necessary
    restart: always
    environment: 
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - .dbdata:/var/lib/mysql
    ports: 
    #Not the same port to avoid conflict with mysql installtion
      - 33067:3306